[[main]]
  identifier = "about"
  name = "O mnie"
  url = "about"
  weight = 1

[[main]]
  identifier = "posts"
  name = "Posty"
  url = "posts"
  weight = 4

# [[main]]
#   identifier = "archive"
#   name = "아카이브"
#   url = "archive"
#   weight = 2

# [[main]]
#   identifier = "gallery"
#   name = "갤러리"
#   url = "gallery"
#   weight = 3
    
# [[main]]
#   parent = "gallery"
#   name = "fiverr"
#   url = "gallery/mine"